name: Build and deploy Node.js app to Azure Web App - emmanode

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: action/checkout@v2
      
      - name: Set up Node.js version
        uses: action/setup-node@v1
        with:
         node-version: '16.x'
       
      - name: npm install, build, and test
        run:
          npm install
          npm run build --if-present
          npm run test --if-present
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@2
        with:
          name: node-app
          path: ../../reactjs_no_modules.zip
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
     name: 'production'
     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
     
    steps:
    - name: Download artifact from build job
      uses: action/download-artifact@v2
      with:
        name: node-app
        
    - name: 'Deploy to Azure Web App'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'emmanode'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a5d49e11921f499eb89a1ba3f33e5d70 }}
        packages: ../../reactjs_no_modules.zip
        
            
        
